[env:watchy-s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600

board_build.arduino.memory_type = qio_qspi
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv

build_flags =
    -DARDUINO_ESP32S3_DEV
    -DBOARD_HAS_PSRAM
    -w

lib_deps =
    zinggjm/GxEPD2@^1.6.0
    adafruit/Adafruit GFX Library@^1.11.0
    adafruit/Adafruit BusIO@^1.16.0
    arduino-libraries/NTPClient@^3.2.1
    arduino-libraries/Arduino_JSON@^0.2.0
    https://github.com/tzapu/WiFiManager.git
    https://github.com/orbitalair/Rtc_Pcf8563.git
